IOP_BIN  = usmb2.irx
IOP_OBJS = ps2iop-compat.o usmb2.o ntlm.o md4c.o hmac-md5.o md5.o imports.o
IOP_CFLAGS = -DUSMB2_FEATURE_OPENDIR -DUSMB2_FEATURE_WRITE

all: $(IOP_BIN)

clean:
	rm -f -r $(IOP_OBJS) $(IOP_BIN)

install: $(IOP_BIN)
	cp $(IOP_BIN) $(PS2SDK)/iop/irx

include $(PS2SDK)/Defs.make
include $(PS2SDK)/samples/Makefile.pref
include $(PS2SDK)/samples/Makefile.iopglobal
